apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynginx
spec:
  replicas: 3
  template:
    metadata:
      name: mynginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
  selector: 
    matchLabels:
      app: nginx
      type: frotend