apiVersion: v1
kind: Service
metadata:
    name: vote-app-svc
    labels:
      app: vote-app-svc
      type: frontend
spec:
    type: ClusterIP
    selector: 
      app: vote-app
      type: frontend
    ports:
     - port: 8080
       targetPort: 80