---
- name: Deploy Spring boot hello world
  hosts: dev
  become: yes
  vars:
     PATH: ""
  tasks:

    - debug:
        var: PATH

    - name: Copy JAR file
      copy:
        src: "{{ item }}"
        dest: /usr/share/tomcat/webapps/spring-boot-app.jar
        owner: tomcat
        group: tomcat
      with_fileglob:
        - "{{ PATH }}/target/*.jar"