apiVersion: v1
kind: Service
metadate:
  name:
  labels:
   name: hello-world-app-svc
   app: hello-world-app
spec:
  type: NodePort
  ports:
   - targetport: 8080
     port: 8080
     nodeport: 30008
  selector:
     matchLabels:
       name: hello-world-app-pod
       app: hello-world-app
       type: frontend
  