apiVersion: apps/vl
kind: Deployment
metadata:
  name: hello-world-app-deploy
  labels:
    name: hello-world-app-deploy
    app: hello-world-app
spec: 
  replicas: 2
  template:
    metadata:
      name: hello-world-app-pod
      labels:
        name: hello-world-app-pod
        app: hello-world-app
        type: frontend
    spec:
      containers:
      - name: hello-world-app-container
        image: 20l35a0114/uday:latest
        ports:
        - containerport: 8080
  selector:
    matchLabels:
       name: hello-world-app-pod
       app: hello-world-app
       type: frontend