apiVersion: v1
kind: Pod
metadata:
   name: result-app
   labels:
      app: result-app
      type: frontend
spec: 
   containers:
    - name: result-app-container
      image: vsiraparapu/result-app
      ports:
        - containerPort: 80