apiVersion: v1
kind: Service
metadata:
    name: spring-boot-app-svc
    labels:
      app: spring-boot-app-svc
      type: frontend
spec:
    type: ClusterIP
    selector: 
      app: spring-boot-app
      type: frontend
    ports:
     - port: 8080
       targetPort: 8080